### ISSUE TITLE
Action name misspells `dependency`

### ISSUE THREAD

**Issue by jsoref** [desbo/merge-pr-action#10]
https://github.com/desbo/merge-pr-action/blob/e5cd901e774423f1087298b4c3479b659bd1f0f9/action.yml#L1

**Comment by desbo** [comment]
Thanks! If you could raise a PR to fix this, I'd appreciate it.

**Comment by jsoref** [comment]
Sure.

Disclaimer, I expect it'll break this link:
https://github.com/marketplace/actions/merge-depenendecy-update-prs

(I know at least one repository that links to it.)

**Comment by desbo** [comment]
Ah, good point. I take it you're referring to scala-steward? Once we fix the typo, I'll take care of relisting the action and raising a PR there. Thanks again.

**Comment by desbo** [comment]
scala-steward PR is [here](https://github.com/scala-steward-org/scala-steward/pull/2129). Cheers.
