### ISSUE TITLE
Fails to parse version for submodule updates

### ISSUE THREAD

**Issue by z0rc** [desbo/merge-pr-action#5]
I'm using dependabot to refresh submodules. merge-pr-action fails with
```
2021/03/22 05:27:03 error parsing upgrade from PR title 0xc000192450: unable to parse 2 versions from Bump vim/pack/03_plugins/start/fugitive from `d70c42a` to `58d2b25`
```
For example check https://github.com/z0rc/dotfiles/runs/2163292375?check_suite_focus=true and PR https://github.com/z0rc/dotfiles/pull/2662

I tried to set `ALLOWED_UPDATE: major`, but this doesn't have an effect in my case.

**Comment by desbo** [comment]
This won't work as the versions are two commit hashes. The action only supports versions in the semver format.

I don't have much experience with dependabot but it seems like it might be able to merge PRs automatically itself? https://dependabot.com/blog/automatic-pull-request-merging/

**Comment by z0rc** [comment]
> merge PRs automatically itself

That was possible earlier, when dependabot was standalone app. After it was acquired by github, and released "v2", this feature was deliberately ommited https://github.com/dependabot/feedback/issues/954

**Comment by desbo** [comment]
Ah, that's a shame... well, for your use case, it seems like you simply want to merge the PR without attempting to detect the type of upgrade (which is obviously impossible to do from a pair of commit hashes) – so an additional option like `ALLOWED_UPDATE: any` to do this would probably be useful?

**Comment by z0rc** [comment]
Yeah, that should work for my case.

**Comment by desbo** [comment]
@z0rc that's released now 👍
