### ISSUE TITLE
Allow running on pull_request_target hook

### ISSUE THREAD

**Issue by z0rc** [desbo/merge-pr-action#8]
Recent changes in dependabot security require using hook `pull_request_target` to be able to use secrets and apply changes to repo in action. https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/

Currently this action doesn't allow this, returning
```
2021/03/23 05:16:51 event is not `pull_request`, exiting
```

**Comment by desbo** [comment]
Thanks for the issue. This should be very straightforward to support by updating the condition here: https://github.com/desbo/merge-pr-action/blob/main/main.go#L35

If you could raise a PR for this I'd appreciate it! Thank you!
